//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyTimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyTimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg of all : .
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best : .
        /// </summary>
        public static string Best {
            get {
                return ResourceManager.GetString("Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best 100  : .
        /// </summary>
        public static string Best100 {
            get {
                return ResourceManager.GetString("Best100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best 12 : .
        /// </summary>
        public static string Best12 {
            get {
                return ResourceManager.GetString("Best12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best 5 : .
        /// </summary>
        public static string Best5 {
            get {
                return ResourceManager.GetString("Best5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current 100 : .
        /// </summary>
        public static string Current100 {
            get {
                return ResourceManager.GetString("Current100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current 12 : .
        /// </summary>
        public static string Current12 {
            get {
                return ResourceManager.GetString("Current12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current 5 : .
        /// </summary>
        public static string Current5 {
            get {
                return ResourceManager.GetString("Current5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultRecordListName {
            get {
                return ResourceManager.GetString("DefaultRecordListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by SkyTimer.
        /// </summary>
        public static string GenMsg {
            get {
                return ResourceManager.GetString("GenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string RecordList_Clear {
            get {
                return ResourceManager.GetString("RecordList_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include scramble in output.
        /// </summary>
        public static string RecordList_IncludeScramble {
            get {
                return ResourceManager.GetString("RecordList_IncludeScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string RecordList_Plot {
            get {
                return ResourceManager.GetString("RecordList_Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RecordList_Rename {
            get {
                return ResourceManager.GetString("RecordList_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Audio Setting.
        /// </summary>
        public static string Timer_Audio {
            get {
                return ResourceManager.GetString("Timer_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic.
        /// </summary>
        public static string Timer_Diagnostic {
            get {
                return ResourceManager.GetString("Timer_Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Precision.
        /// </summary>
        public static string Timer_Double {
            get {
                return ResourceManager.GetString("Timer_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available. Update?.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available, please download it..
        /// </summary>
        public static string UpdateNotification {
            get {
                return ResourceManager.GetString("UpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst : .
        /// </summary>
        public static string Worst {
            get {
                return ResourceManager.GetString("Worst", resourceCulture);
            }
        }
    }
}
